# Generated by Django 5.0.6 on 2024-07-08 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('ECE', 'Electronics and Communication Engineering')], max_length=50, unique=True)),
                ('open_seats', models.IntegerField(default=0)),
                ('open_pwd_seats', models.IntegerField(default=0)),
                ('ews_seats', models.IntegerField(default=0)),
                ('ews_pwd_seats', models.IntegerField(default=0)),
                ('sc_seats', models.IntegerField(default=0)),
                ('sc_pwd_seats', models.IntegerField(default=0)),
                ('st_seats', models.IntegerField(default=0)),
                ('st_pwd_seats', models.IntegerField(default=0)),
                ('obc_ncl_seats', models.IntegerField(default=0)),
                ('obc_ncl_pwd_seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('cgpa', models.FloatField()),
                ('jee_rank', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('preference1', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('ECE', 'Electronics and Communication Engineering')], max_length=50, null=True)),
                ('preference2', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('ECE', 'Electronics and Communication Engineering')], max_length=50, null=True)),
                ('preference3', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('ECE', 'Electronics and Communication Engineering')], max_length=50, null=True)),
                ('allocated_branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('ECE', 'Electronics and Communication Engineering')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
